/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  start: [{ type: "autogenerated", dirName: "start" }],
  bridges: [{ type: "autogenerated", dirName: "bridges" }],
  developers: [{ type: "autogenerated", dirName: "developers" }],
  faq: [{ type: "autogenerated", dirName: "faq" }],
  technicalGuides: [
    { type: "autogenerated", dirName: "technicalguides" },
    {
      type: "category",
      label: "About",
      collapsible: true,
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "about" }],
    },
  ],
  termsConditions: [{ type: "autogenerated", dirName: "terms-conditions" }],
  tools: [{ type: "autogenerated", dirName: "tools" }],
};

module.exports = sidebars;

